USE RTK;

SET @script = '2020-09-30-20-51_RebalanceSubAccessories.sql';

DELIMITER $$

DROP PROCEDURE IF EXISTS sp $$

CREATE PROCEDURE sp(
	IN scriptName VARCHAR(255)
)

BEGIN
	IF NOT EXISTS (SELECT * FROM MigrationHistory WHERE Script = scriptName) THEN
		UPDATE Items SET ItmPthId = '1', ItmIdentifier = 'war_amulet', ItmDescription = 'War amulet', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '878', ItmIconColor = '1', ItmSex = '2', ItmLevel = '11', ItmMark = '0', ItmDurability = '10000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '1', ItmDam = '1', ItmVita = '100', ItmMana = '0', ItmMight = '1', ItmWill = '0', ItmGrace = '0', ItmProtection = '0', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '10000', ItmSellPrice = '5000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26048';
		UPDATE Items SET ItmPthId = '2', ItmIdentifier = 'battle_amulet', ItmDescription = 'Battle amulet', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '879', ItmIconColor = '1', ItmSex = '2', ItmLevel = '11', ItmMark = '0', ItmDurability = '9000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '0', ItmDam = '2', ItmVita = '50', ItmMana = '50', ItmMight = '0', ItmWill = '0', ItmGrace = '1', ItmProtection = '0', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '10000', ItmSellPrice = '5000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26050';
		UPDATE Items SET ItmPthId = '3', ItmIdentifier = 'magic_amulet', ItmDescription = 'Magic amulet', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '880', ItmIconColor = '1', ItmSex = '2', ItmLevel = '11', ItmMark = '0', ItmDurability = '8000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-1', ItmHit = '0', ItmDam = '0', ItmVita = '0', ItmMana = '100', ItmMight = '0', ItmWill = '1', ItmGrace = '0', ItmProtection = '0', ItmHealing = '1', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '10000', ItmSellPrice = '5000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26052';
		UPDATE Items SET ItmPthId = '4', ItmIdentifier = 'love_amulet', ItmDescription = 'Love amulet', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '881', ItmIconColor = '1', ItmSex = '2', ItmLevel = '11', ItmMark = '0', ItmDurability = '8000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-1', ItmHit = '0', ItmDam = '0', ItmVita = '50', ItmMana = '50', ItmMight = '0', ItmWill = '0', ItmGrace = '0', ItmProtection = '0', ItmHealing = '1', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '10000', ItmSellPrice = '5000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26054';
		UPDATE Items SET ItmPthId = '1', ItmIdentifier = 'war_rune', ItmDescription = 'War rune', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '878', ItmIconColor = '0', ItmSex = '2', ItmLevel = '39', ItmMark = '0', ItmDurability = '40000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-4', ItmHit = '2', ItmDam = '1', ItmVita = '200', ItmMana = '50', ItmMight = '1', ItmWill = '0', ItmGrace = '0', ItmProtection = '1', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '15000', ItmSellPrice = '7500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26049';
		UPDATE Items SET ItmPthId = '2', ItmIdentifier = 'battle_rune', ItmDescription = 'Battle rune', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '879', ItmIconColor = '0', ItmSex = '2', ItmLevel = '39', ItmMark = '0', ItmDurability = '35000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-3', ItmHit = '1', ItmDam = '2', ItmVita = '150', ItmMana = '100', ItmMight = '0', ItmWill = '0', ItmGrace = '1', ItmProtection = '1', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '15000', ItmSellPrice = '7500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26051';
		UPDATE Items SET ItmPthId = '3', ItmIdentifier = 'magic_rune', ItmDescription = 'Magic rune', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '880', ItmIconColor = '0', ItmSex = '2', ItmLevel = '39', ItmMark = '0', ItmDurability = '30000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-1', ItmHit = '0', ItmDam = '0', ItmVita = '50', ItmMana = '200', ItmMight = '0', ItmWill = '2', ItmGrace = '0', ItmProtection = '1', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '15000', ItmSellPrice = '7500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26053';
		UPDATE Items SET ItmPthId = '4', ItmIdentifier = 'love_rune', ItmDescription = 'Love rune', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '881', ItmIconColor = '0', ItmSex = '2', ItmLevel = '39', ItmMark = '0', ItmDurability = '30000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '0', ItmDam = '0', ItmVita = '100', ItmMana = '150', ItmMight = '0', ItmWill = '0', ItmGrace = '0', ItmProtection = '1', ItmHealing = '1', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '15000', ItmSellPrice = '7500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '1', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26055';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'scorched_bone', ItmDescription = 'Scorched bone', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '2233', ItmIconColor = '2', ItmSex = '2', ItmLevel = '68', ItmMark = '0', ItmDurability = '25000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '0', ItmDam = '0', ItmVita = '500', ItmMana = '1000', ItmMight = '0', ItmWill = '2', ItmGrace = '0', ItmProtection = '4', ItmHealing = '2', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '20000', ItmSellPrice = '10000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '26010';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'bone', ItmDescription = 'Bone', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '2233', ItmIconColor = '23', ItmSex = '2', ItmLevel = '68', ItmMark = '0', ItmDurability = '30000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '0', ItmHit = '2', ItmDam = '2', ItmVita = '1000', ItmMana = '500', ItmMight = '2', ItmWill = '0', ItmGrace = '4', ItmProtection = '0', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '40', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '20000', ItmSellPrice = '10000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '10007';
		UPDATE Items SET ItmPthId = '1', ItmIdentifier = 'azure_diamond', ItmDescription = 'Azure diamond', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '22', ItmSex = '2', ItmLevel = '99', ItmMark = '0', ItmDurability = '50000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-1', ItmHit = '1', ItmDam = '1', ItmVita = '3000', ItmMana = '0', ItmMight = '2', ItmWill = '0', ItmGrace = '0', ItmProtection = '2', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '25000', ItmSellPrice = '12500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27004';
		UPDATE Items SET ItmPthId = '2', ItmIdentifier = 'jade_diamond', ItmDescription = 'Jade diamond', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '18', ItmSex = '2', ItmLevel = '99', ItmMark = '0', ItmDurability = '40000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-1', ItmHit = '0', ItmDam = '2', ItmVita = '2000', ItmMana = '1000', ItmMight = '0', ItmWill = '0', ItmGrace = '2', ItmProtection = '2', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '25000', ItmSellPrice = '12500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27002';
		UPDATE Items SET ItmPthId = '3', ItmIdentifier = 'lazuline_diamond', ItmDescription = 'Lazuline diamond', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '1', ItmSex = '2', ItmLevel = '99', ItmMark = '0', ItmDurability = '35000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-1', ItmHit = '0', ItmDam = '0', ItmVita = '0', ItmMana = '2250', ItmMight = '0', ItmWill = '4', ItmGrace = '0', ItmProtection = '2', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '25000', ItmSellPrice = '12500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27005';
		UPDATE Items SET ItmPthId = '4', ItmIdentifier = 'forest_diamond', ItmDescription = 'Forest diamond', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '15', ItmSex = '2', ItmLevel = '99', ItmMark = '0', ItmDurability = '35000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-1', ItmHit = '0', ItmDam = '0', ItmVita = '750', ItmMana = '1500', ItmMight = '0', ItmWill = '2', ItmGrace = '0', ItmProtection = '2', ItmHealing = '2', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '25000', ItmSellPrice = '12500', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27003';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'shade_diamond', ItmDescription = 'Shade diamond', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '23', ItmSex = '2', ItmLevel = '99', ItmMark = '1', ItmDurability = '40000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '0', ItmDam = '0', ItmVita = '0', ItmMana = '3000', ItmMight = '0', ItmWill = '5', ItmGrace = '0', ItmProtection = '3', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '30000', ItmSellPrice = '15000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27007';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'night_diamond', ItmDescription = 'Night diamond', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '28', ItmSex = '2', ItmLevel = '99', ItmMark = '1', ItmDurability = '40000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '0', ItmDam = '3', ItmVita = '4000', ItmMana = '0', ItmMight = '3', ItmWill = '0', ItmGrace = '0', ItmProtection = '3', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '135', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '30000', ItmSellPrice = '15000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27006';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'cerise_diamond', ItmDescription = 'Cerise diamond', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '21', ItmSex = '2', ItmLevel = '99', ItmMark = '2', ItmDurability = '50000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '0', ItmDam = '0', ItmVita = '0', ItmMana = '3750', ItmMight = '0', ItmWill = '6', ItmGrace = '0', ItmProtection = '3', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '40000', ItmSellPrice = '20000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27009';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'crimson_diamond', ItmDescription = 'Crimson diamond', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '31', ItmSex = '2', ItmLevel = '99', ItmMark = '2', ItmDurability = '50000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-2', ItmHit = '0', ItmDam = '3', ItmVita = '5000', ItmMana = '0', ItmMight = '3', ItmWill = '0', ItmGrace = '0', ItmProtection = '3', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '138', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '40000', ItmSellPrice = '20000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27008';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'lucent_diamond', ItmDescription = 'Lucent diamond', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '30', ItmSex = '2', ItmLevel = '99', ItmMark = '3', ItmDurability = '60000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-3', ItmHit = '0', ItmDam = '0', ItmVita = '0', ItmMana = '4500', ItmMight = '0', ItmWill = '7', ItmGrace = '0', ItmProtection = '4', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '50000', ItmSellPrice = '25000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27011';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'searing_diamond', ItmDescription = 'Searing diamond', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '20', ItmSex = '2', ItmLevel = '99', ItmMark = '3', ItmDurability = '60000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-3', ItmHit = '0', ItmDam = '3', ItmVita = '6000', ItmMana = '0', ItmMight = '4', ItmWill = '0', ItmGrace = '0', ItmProtection = '4', ItmHealing = '0', ItmWisdom = '0', ItmMightRequired = '140', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '50000', ItmSellPrice = '25000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27010';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'radiant_diamond', ItmDescription = 'Radiant diamond', ItmType = '9', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '11', ItmSex = '2', ItmLevel = '99', ItmMark = '4', ItmDurability = '70000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-3', ItmHit = '0', ItmDam = '0', ItmVita = '0', ItmMana = '6000', ItmMight = '0', ItmWill = '7', ItmGrace = '0', ItmProtection = '4', ItmHealing = '15', ItmWisdom = '0', ItmMightRequired = '0', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '60000', ItmSellPrice = '30000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27012';
		UPDATE Items SET ItmPthId = '0', ItmIdentifier = 'torrid_diamond', ItmDescription = 'Torrid diamond', ItmType = '10', ItmSkinnable = '0', ItmStackAmount = '1', ItmMaximumAmount = '0', ItmLook = '0', ItmLookColor = '0', ItmIcon = '3253', ItmIconColor = '13', ItmSex = '2', ItmLevel = '99', ItmMark = '4', ItmDurability = '70000', ItmMinimumSDamage = '0', ItmMaximumSDamage = '0', ItmMinimumLDamage = '0', ItmMaximumLDamage = '0', ItmArmor = '-3', ItmHit = '0', ItmDam = '3', ItmVita = '8000', ItmMana = '0', ItmMight = '4', ItmWill = '0', ItmGrace = '0', ItmProtection = '4', ItmHealing = '15', ItmWisdom = '0', ItmMightRequired = '145', ItmExchangeable = '0', ItmDepositable = '0', ItmDroppable = '0', ItmCon = '0', ItmSound = '331', ItmText = '', ItmBuyPrice = '60000', ItmSellPrice = '30000', ItmBuyText = '', ItmThrown = '0', ItmThrownConfirm = '1', ItmRepairable = '1', ItmIndestructible = '0', ItmTimer = '0', ItmBoD = '0', ItmProtected = '0', ItmUnequip = '0' WHERE ItmId = '27013';

		INSERT INTO `MigrationHistory` (Script,Timestamp) VALUES (scriptName,NOW());
	ELSE
		SELECT CONCAT(scriptName, ' was skipped because it is already present in the migration history.') AS '';
	END IF;
END $$

CALL sp(@script) $$

DROP PROCEDURE IF EXISTS sp $$
 
DELIMITER ;
